[project]
name = "airbnb-elt"
version = "0.1.0"
description = "Airbnb ELT GCloud Project"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dbt-core>=1.11.3",
    "dbt-snowflake>=1.11.1",
]
